src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="posts")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @Assert\File(mimeTypes={"image/jpeg"}, maxSize="8000000M")
     */
    private $image;

    /**
     * @ORM\Column(type="integer")
     */
    private $download = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $vue = 0;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Users", inversedBy="posts")
     */
    private $likes;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_likes = 0;
    

    public function __construct()
    {
        $this->created_at = new \DateTime('now', new \DateTimeZone('Europe/Paris'));
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDownload(): ?int
    {
        return $this->download;
    }

    public function setDownload(int $download): self
    {
        $this->download = $download;

        return $this;
    }

    public function getVue(): ?int
    {
        return $this->vue;
    }

    public function setVue(int $vue): self
    {
        $this->vue = $vue;

        return $this;
    }

    /**
     * @return Collection|Users[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Users $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
        }

        return $this;
    }

    public function removeLike(Users $like): self
    {
        if ($this->likes->contains($like)) {
            $this->likes->removeElement($like);
        }

        return $this;
    }

    public function getNbLikes(): ?int
    {
        return $this->nb_likes;
    }

    public function setNbLikes(int $nb_likes): self
    {
        $this->nb_likes = $nb_likes;

        return $this;
    }

}

src/Form/PostForm.php
<?php


namespace App\Form;


use App\Entity\Category;
use App\Entity\Post;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class)
            ->add('content', TextareaType::class)
            ->add('image', FileType::class, [
                'required' => false,
                'data_class' => null
            ])
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'placeholder' => 'Sélectionner Catégorie',
                'choice_label' => 'name',
                'required' => false
            ])
            ;

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults([
                'data_class' => Post::class
            ]);
    }

}

src/Controller/PostController.php
<?php


namespace App\Controller;


use App\Entity\Post;
use App\Entity\Users;
use App\Form\PostForm;
use App\Repository\PostRepository;
use App\Services\ImageUpload;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PostController extends AbstractController
{

    /**
     * @Route("/post", name="list_post")
     */
    public function listPost()
    {


        $posts = $this->getDoctrine()->getRepository(Post::class)->findAll();


        return $this->render('/Posts/index_post.html.twig', [
            'title' => 'Posts',
            'posts' => $posts,
        ]);

    }

    /**
     * @Route("/post/new", name="new_post")
     */
    public function newPost(Request $request, ImageUpload $upload)
    {
        $post = new Post();

        $form = $this->createForm(PostForm::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){

            $image = $form->get('image')->getData();
            if (isset($image)){
                $imagename = $upload->upload($image);
                $post->setImage($imagename);
            }
            $em = $this->getDoctrine()->getManager();
            $em->persist($post);
            $em->flush();

            return $this->redirectToRoute('list_post');
        }

        return $this->render('/Posts/new_post.html.twig', [
            'form' => $form->createView(),
            'title' => 'Créer Post'
        ]);
    }

    /**
     * @Route("/post/edit/{id}", name="edit_post")
     */
    public function editPost(Request $request, Post $post, ImageUpload $upload)
    {

        $id = $post->getId();

        $form = $this->createForm(PostForm::class, $post);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()){
            $image = $form->get('image')->getData();
            if (isset($image)){
                $imagename = $upload->upload($image);
                $post->setImage($imagename);
            }else{
                $post->setImage($post->getImage());
            }
            $em = $this->getDoctrine()->getManager();
            $em->getRepository(Post::class);
            $em->persist($post);
            $post->setUpdatedAt(new \DateTime('now', new \DateTimeZone('Europe/Paris')));
            $em->flush();

            return $this->redirectToRoute('list_post');
        }

        return $this->render('/Posts/edit_post.html.twig', [
            'id' => $id,
            'title' => 'Edit',
            'form' => $form->createView(),
            'post' => $post
        ]);
    }

    /**
     * @Route("/post/show/{id}/{userid}", name="show_post")
     * @param PostRepository $postRepository
     * @param $id
     * @param $userid
     * @return Response
     */
    public function showPost(PostRepository $postRepository, $id, $userid)
    {

        $entitymanager = $this->getDoctrine()->getManager();
        $cat = $postRepository->findCategory($id);
        $posts = $this->getDoctrine()->getManager()->getRepository(Post::class)->find($id);

        $name = $posts->getImage();

        $image = 'images/'.$name;

        $vue = $posts->getVue();

        $entitymanager->persist($posts->setVue($vue+1));
        $entitymanager->flush();

        $likepost = $postRepository->findUserid($posts->getId());

        foreach ($likepost as $value){
//            var_dump($value);
        }

        if ($name){
            $exif = exif_read_data($image, '0', true);
            return $this->render('/Posts/show_post.html.twig', [
                'title' => 'Détail',
                'posts' => $posts,
                'category' => $cat,
                'exif' => $exif,
                'likepost' => $value
            ]);
        } else {
            return $this->render('/Posts/show_post.html.twig', [
                'title' => 'Détail',
                'posts' => $posts,
                'category' => $cat,
            ]);
        }
    }

    /**
     * @Route("/post/delete/{id}", name="delete_post")
     */
    public function removePost($id)
    {
        $entitymanager = $this->getDoctrine()->getManager();
        $post = $entitymanager->getRepository(Post::class)->find($id);

        $entitymanager->remove($post);
        $entitymanager->flush();

        return $this->redirectToRoute('list_post');
    }

    /**
     * @param Post $post
     * @Route("/download/image/{id}", name="download_actio")
     * @return BinaryFileResponse
     */
    public function DownloadAction(Post $post)
    {

        $entitymanager = $this->getDoctrine()->getManager();
        $imagename = $post->getImage();
        $imagepath = $this->getParameter('images_directory').$imagename;

        $download = $post->getDownload();

        $entitymanager->persist($post->setDownload($download + 1));
        $entitymanager->flush();

        return $this->file($imagepath);

    }

    /**
     * @param Post $post
     * @param $user_id
     * @return RedirectResponse
     * @Route("/like/post/{id}/{user_id}", name="like_action")
     */
    public function LikeAction(Post $post, $user_id)
    {
        $entitymanager = $this->getDoctrine()->getManager();
        $users = $this->getDoctrine()->getRepository(Users::class)->find($user_id);

        $entitymanager->persist($users->addPost($post));
        $entitymanager->flush();

        $entitymanager->persist($post->setNbLikes($post->getNbLikes()+1));
        $entitymanager->flush();


        return $this->redirectToRoute('show_post', [
            'id' => $post->getId(),
            'userid' => $users->getId()
        ]);

    }

    /**
     * @param Post $post
     * @param $user_id
     * @return RedirectResponse
     * @Route("/dislike/post/{id}/{user_id}", name="dislike_action")
     */
    public function DisLikeAction(Post $post, $user_id)
    {
        $entitymanager =$this->getDoctrine()->getManager();
        $users = $this->getDoctrine()->getRepository(Users::class)->find($user_id);

        $entitymanager->persist($users->removePost($post));
        $entitymanager->flush();

        $entitymanager->persist($post->setNbLikes($post->getNbLikes()-1));
        $entitymanager->flush();


        return $this->redirectToRoute('show_post', [
            'id' => $post->getId(),
            'userid' => $users->getId()
        ]);

    }
}

templates/Posts/edit_post.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ parent() }}

    {{ form_start(form, { 'attr' : { 'class' : 'form_post' }}) }}

    <div class="titre_post">
        {{ form_label(form.title, 'Titre', { 'label_attr' : { 'class' : 'label_newpost' }}) }}
        {% for error in form.title.vars.errors %}
            <p class="error_newpost">{{ error.message }}</p>
        {% endfor %}
        <br>{{ form_widget(form.title, { 'attr' : { 'class' : 'widget_titre' }}) }}
    </div>
    <div class="content_post">
        {{ form_label(form.content, 'Contenu', { 'label_attr' : { 'class' : 'label_newpost' }}) }}
        {% for error in form.content.vars.errors %}
            <p class="error_newpost">{{ error.message }}</p>
        {% endfor %}
        <br>{{ form_widget(form.content, { 'attr' : { 'class' : 'widget_content' }}) }}
    </div>
    <div class="content_post">
        <img src="{{ asset('images/' ~ post.image) }}" alt="" width="126px" height="126px">
        <br>{{ form_label(form.image, 'Image en JPEG', { 'label_attr' : { 'class' : 'label_newpost' }}) }}
        {% for error in form.image.vars.errors %}
            <p class="error_newpost">{{ error.message }}</p>
        {% endfor %}
        <br>{{ form_widget(form.image, { 'attr' : { 'class' : 'widget_image' }}) }}
    </div>
    <div>
        {{ form_label(form.category, 'Choix de la Catégorie', { 'label_attr' : { 'class' : 'label_newpost' }}) }}
        <br>{{ form_widget(form.category, { 'attr' : { 'class' : 'widget_category' }}) }}
    </div>

    <input type="submit" value="Enregistrer" class="submit_newpost">

    {{ form_end(form) }}

{% endblock body %}

templates/Posts/index_post.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ parent() }}
    <h2>Voici la liste des posts différents qui existent sur le site</h2>

    <h4 class="titre_tablepost">Liste des Posts</h4>
    <table class="table_post">
        <tr class="table_ligne1">
            <td>Titre</td>
            <td>Contenu</td>
            <td>Date de création</td>
            <td>Date de Modification</td>
            <td>Détail</td>
            <td>Action</td>
        </tr>
        {% for post in posts %}
            <tr class="lignepost">
                <td>{{ post.title }}</td>
                <td>{{ post.content|truncate(20, false, '...') }}</td>
                <td>{{ post.createdAt|date('d/m/Y') }}</td>
                {% if post.updatedAt is not null %}
                    <td>{{ post.updatedAt|date('d/m/Y') }}</td>
                {% elseif post.updatedAt is null %}
                    <td>Non Modifié</td>
                {% endif %}
                <td><a href="{{ path('show_post', { 'id' : post.id, 'userid' : app.user.id }) }}">Voir</a></td>
                <td><a href="{{ path('edit_post', { 'id' : post.id }) }}" class="lien_action">Edit</a>
                    <a class="lien_action" href="{{ path('delete_post', { 'id' : post.id }) }}">Delete</a></td>
            </tr>

        {% endfor %}
    </table>

    <p>Voici le lien pour créer un nouveau post : <a class="lien_nouveau" href="{{ path('new_post') }}">Nouveau</a></p>

{% endblock body %}

templates/Posts/new_post.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ parent() }}

    {{ form_start(form, { 'attr' : { 'class' : 'form_post' }}) }}

    <div class="titre_post">
        {{ form_label(form.title, 'Titre', { 'label_attr' : { 'class' : 'label_newpost' }}) }}
        {% for error in form.title.vars.errors %}
            <p class="error_newpost">{{ error.message }}</p>
        {% endfor %}
        <br>{{ form_widget(form.title, { 'attr' : { 'class' : 'widget_titre' }}) }}
    </div>
    <div class="content_post">
        {{ form_label(form.content, 'Contenu', { 'label_attr' : { 'class' : 'label_newpost' }}) }}
        {% for error in form.content.vars.errors %}
            <p class="error_newpost">{{ error.message }}</p>
        {% endfor %}
        <br>{{ form_widget(form.content, { 'attr' : { 'class' : 'widget_content' }}) }}
    </div>
    <div class="content_post">
        {{ form_label(form.image, 'Image en JPEG', { 'label_attr' : { 'class' : 'label_newpost' }}) }}
        {% for error in form.image.vars.errors %}
            <p class="error_newpost">{{ error.message }}</p>
        {% endfor %}
        <br>{{ form_widget(form.image, { 'attr' : { 'class' : 'widget_image' }}) }}
    </div>
    <div>
        {{ form_label(form.category, 'Choix de la Catégorie', { 'label_attr' : { 'class' : 'label_newpost' }}) }}
        <br>{{ form_widget(form.category, { 'attr' : { 'class' : 'widget_category' }}) }}
    </div>

    <input type="submit" value="Enregistrer" class="submit_newpost">

    {{ form_end(form) }}

{% endblock body %}

templates/Posts/show_post.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ parent() }}


    <div class="show-post">
        <ul>
            <li>Titre : {{ posts.title }}</li>
            <li>Contenu : {{ posts.content }}</li>
            <li>Date de Création : {{ posts.createdAt|date('d/m/Y') }}</li>
            <li>Date de modification : {{ posts.updatedAt|date('d/m/Y') }}</li>
            <li>Categorie :
                {% if category[0]['name'] is not null %}
                {{ category[0]['name'] }}</li>
            {% else %}
                Aucune Catégorie</li>
            {% endif %}
        </ul>
        {% if exif is defined %}
            <ul>
                Image: <br><img src="{{ asset('images/' ~ posts.image) }}" alt="" width="256px" height="256px" class="image_post">
            </ul>
            {% if exif.EXIF is defined %}
            <ul class="detail-images">
                <li>Type d'image : {{ exif.FILE.MimeType }}</li>
                <li>Poids de l'image : {{ exif.FILE.FileSize|length }} Mb</li>
                <li>Date de prise : {{ exif.EXIF.DateTimeOriginal| date('d/m/Y H:m') }}</li>
                <li>Largeur de l'image : {{ exif.EXIF.ExifImageWidth }} pixels</li>
                <li>Longueur de l'image : {{ exif.EXIF.ExifImageLength }} pixels</li>
                <button id="download_image" name="download_image">
                    <a href="{{ path('download_actio', { 'id' : posts.id }) }}">Télécharger</a>
                </button>
                {% if app.user.id not in likepost %}
                            <button>
                                <a href="{{ path('like_action', { 'id': posts.id, 'user_id' : app.user.id }) }}">J'aime</a>
                            </button>
                {% elseif app.user.id in likepost %}
                            <button>
                                <a href="{{ path('dislike_action', { 'id': posts.id, 'user_id' : app.user.id }) }}">J'aime pas</a>
                            </button>
                {% endif %}
            </ul>
        {% endif %}
        {% endif %}


    </div>
    <div class="clear"></div>

    <div class="button-show">
        <button><a href="{{ path('list_post') }}">Retour</a></button>
        <button><a href="{{ path('edit_post', { 'id' : posts.id }) }}">Editer</a></button>
        <button><a href="{{ path('delete_post', { 'id' : posts.id }) }}">Supprimer</a></button>
    </div>

{% endblock body %}